#!/bin/bash

# 颜色定义
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
MAGENTA="\033[35m"
CYAN="\033[36m"
WHITE="\033[37m"
BOLD="\033[1m"
UNDERLINE="\033[4m"
RESET="\033[0m"

# 图标定义
ICON_OK="${GREEN}✓${RESET}"
ICON_WARN="${YELLOW}⚠${RESET}"
ICON_ERROR="${RED}✗${RESET}"
ICON_INFO="${BLUE}ℹ${RESET}"
ICON_CONFIG="${CYAN}⚙${RESET}"
ICON_FOLDER="${MAGENTA}📁${RESET}"

# 显示横幅
show_banner() {
    clear
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${WHITE}        SSH密钥与配置管理脚本         ${RESET}"
    echo -e "${BOLD}${YELLOW}        多功能SSH安全管理工具         ${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n"
}

# 功能1: 创建和管理SSH密钥
function_create_keys() {
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${WHITE}           SSH密钥创建与管理           ${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n"
    
    # 1. 检查并安装SSH
    echo -e "${ICON_INFO} ${BOLD}检查SSH安装状态...${RESET}"
    if command -v ssh >/dev/null 2>&1 && command -v ssh-keygen >/dev/null 2>&1; then
        echo -e "  ${ICON_OK} SSH已安装"
    else
        echo -e "  ${ICON_WARN} SSH未安装，正在安装..."
        if command -v apt-get >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y openssh-client openssh-server
        elif command -v yum >/dev/null 2>&1; then
            sudo yum install -y openssh-clients openssh-server
        elif command -v dnf >/dev/null 2>&1; then
            sudo dnf install -y openssh-clients openssh-server
        elif command -v zypper >/dev/null 2>&1; then
            sudo zypper install -y openssh
        else
            echo -e "  ${ICON_ERROR} 无法自动安装SSH，请手动安装"
            return 1
        fi
        
        if [ $? -eq 0 ]; then
            echo -e "  ${ICON_OK} SSH安装成功"
        else
            echo -e "  ${ICON_ERROR} SSH安装失败"
            return 1
        fi
    fi
    
    # 2. 创建密钥保存目录
    echo -e "\n${ICON_INFO} ${BOLD}设置密钥存储路径...${RESET}"
    KEY_DIR="/root/.ssh"
    if [ ! -d "$KEY_DIR" ]; then
        mkdir -p "$KEY_DIR"
        chmod 700 "$KEY_DIR"
        echo -e "  ${ICON_OK} 创建目录: $KEY_DIR"
    else
        echo -e "  ${ICON_OK} 目录已存在: $KEY_DIR"
    fi
    
    # 3. 获取密钥文件名
    echo -e "\n${ICON_INFO} ${BOLD}请输入密钥文件名${RESET}"
    echo -e "  ${YELLOW}提示: 不要输入路径，只输入文件名${RESET}"
    echo -e "  ${YELLOW}默认: ${GREEN}id_ed25519${RESET}"
    echo -n "  文件名: "
    read -r KEY_NAME
    
    if [ -z "$KEY_NAME" ]; then
        KEY_NAME="id_ed25519"
    fi
    
    # 移除可能的路径部分
    KEY_NAME=$(basename "$KEY_NAME")
    
    # 检查文件是否已存在
    KEY_PATH="$KEY_DIR/$KEY_NAME"
    if [ -f "$KEY_PATH" ] || [ -f "$KEY_PATH.pub" ]; then
        echo -e "\n${ICON_WARN} ${BOLD}警告: 密钥文件已存在${RESET}"
        echo -e "  ${YELLOW}1) 覆盖现有文件${RESET}"
        echo -e "  ${YELLOW}2) 使用其他文件名${RESET}"
        echo -e "  ${YELLOW}3) 取消操作${RESET}"
        echo -n "  请选择 (1/2/3): "
        read -r OVERRIDE_CHOICE
        
        case $OVERRIDE_CHOICE in
            1)
                echo -e "  ${ICON_WARN} 覆盖现有密钥文件..."
                rm -f "$KEY_PATH" "$KEY_PATH.pub" 2>/dev/null
                ;;
            2)
                echo -n "  请输入新的文件名: "
                read -r NEW_KEY_NAME
                KEY_NAME=$(basename "$NEW_KEY_NAME")
                KEY_PATH="$KEY_DIR/$KEY_NAME"
                ;;
            3)
                echo -e "  ${ICON_INFO} 操作取消"
                return
                ;;
            *)
                echo -e "  ${ICON_ERROR} 无效选择，操作取消"
                return
                ;;
        esac
    fi
    
    # 4. 生成密钥对
    echo -e "\n${ICON_INFO} ${BOLD}生成ED25519密钥对...${RESET}"
    echo -e "  ${YELLOW}提示:${RESET}"
    echo -e "  ${YELLOW}1) 按Enter跳过密码设置（无密码密钥）${RESET}"
    echo -e "  ${YELLOW}2) 输入密码以增强安全性（每次使用需输入）${RESET}"
    
    ssh-keygen -t ed25519 -f "$KEY_PATH" -C "Generated by SSH Manager on $(date '+%Y-%m-%d')"
    
    if [ $? -eq 0 ]; then
        echo -e "\n  ${ICON_OK} ${GREEN}密钥对生成成功${RESET}"
    else
        echo -e "  ${ICON_ERROR} 密钥生成失败"
        return 1
    fi
    
    # 5. 检查并安装puttygen（如果可用）
    echo -e "\n${ICON_INFO} ${BOLD}检查PuTTY密钥转换工具...${RESET}"
    CONVERT_PUTTY=false
    if command -v puttygen >/dev/null 2>&1; then
        echo -e "  ${ICON_OK} puttygen已安装"
        CONVERT_PUTTY=true
    else
        echo -e "  ${ICON_WARN} puttygen未安装，正在尝试安装..."
        if command -v apt-get >/dev/null 2>&1; then
            sudo apt-get install -y putty-tools
        elif command -v yum >/dev/null 2>&1; then
            sudo yum install -y putty
        elif command -v dnf >/dev/null 2>&1; then
            sudo dnf install -y putty
        else
            echo -e "  ${ICON_WARN} 无法自动安装puttygen，跳过密钥转换"
        fi
        
        if command -v puttygen >/dev/null 2>&1; then
            echo -e "  ${ICON_OK} puttygen安装成功"
            CONVERT_PUTTY=true
        else
            echo -e "  ${ICON_WARN} puttygen安装失败，跳过密钥转换"
        fi
    fi
    
    # 6. 转换密钥格式（如果puttygen可用）
    if [ "$CONVERT_PUTTY" = true ]; then
        echo -e "\n${ICON_INFO} ${BOLD}转换密钥格式为PuTTY格式...${RESET}"
        cd "$KEY_DIR" || return 1
        
        # 生成PPK格式（用于PuTTY）
        PUTTY_KEY="${KEY_NAME}_putty.ppk"
        if puttygen "$KEY_NAME" -o "$PUTTY_KEY" 2>/dev/null; then
            echo -e "  ${ICON_OK} PuTTY格式密钥生成成功"
        else
            echo -e "  ${ICON_WARN} PuTTY格式转换失败"
        fi
        
        # 生成PEM格式（用于OpenSSH）
        PEM_KEY="${KEY_NAME}.pem"
        if [ -f "$PUTTY_KEY" ] && puttygen "$PUTTY_KEY" -O private-openssh -o "$PEM_KEY" 2>/dev/null; then
            echo -e "  ${ICON_OK} PEM格式密钥生成成功"
        else
            echo -e "  ${ICON_WARN} PEM格式转换失败"
        fi
    else
        echo -e "\n${ICON_WARN} ${BOLD}跳过PuTTY密钥转换（puttygen不可用）${RESET}"
    fi
    
    # 7. 导入公钥到authorized_keys
    echo -e "\n${ICON_INFO} ${BOLD}导入公钥到authorized_keys...${RESET}"
    AUTH_KEYS="$KEY_DIR/authorized_keys"
    
    if [ ! -f "$AUTH_KEYS" ]; then
        touch "$AUTH_KEYS"
        chmod 600 "$AUTH_KEYS"
        echo -e "  ${ICON_OK} 创建authorized_keys文件"
    fi
    
    # 检查公钥是否已存在
    PUB_KEY_CONTENT=$(cat "$KEY_PATH.pub")
    if grep -q "$PUB_KEY_CONTENT" "$AUTH_KEYS" 2>/dev/null; then
        echo -e "  ${ICON_WARN} 公钥已存在于authorized_keys中"
    else
        cat "$KEY_PATH.pub" >> "$AUTH_KEYS"
        echo -e "  ${ICON_OK} 公钥已添加到authorized_keys"
    fi
    
    # 8. 设置正确的权限
    chmod 600 "$KEY_PATH" 2>/dev/null
    chmod 644 "$KEY_PATH.pub" 2>/dev/null
    chown -R "$(whoami):$(id -gn)" "$KEY_DIR" 2>/dev/null
    
    # 9. 显示结果摘要 - 重新设计输出格式
    echo -e "\n${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${WHITE}             密钥生成完成！             ${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n"
    
    # 生成的密钥文件
    echo -e "${BOLD}${GREEN}📁 生成的密钥文件:${RESET}"
    echo -e "${CYAN}────────────────────────────────────────${RESET}"
    
    echo -e "${BOLD}${WHITE}私钥 (Private Key):${RESET}"
    echo -e "  ${RED}⚠ 绝密文件，请妥善保管${RESET}"
    echo -e "  ${GREEN}位置:${RESET} ${KEY_PATH}"
    echo -e "  ${GREEN}权限:${RESET} 600 (仅所有者读写)"
    echo -e "  ${GREEN}大小:${RESET} $(stat -c%s "$KEY_PATH" 2>/dev/null || echo "未知") 字节"
    
    echo -e "\n${BOLD}${WHITE}公钥 (Public Key):${RESET}"
    echo -e "  ${CYAN}✓ 可公开，用于服务端认证${RESET}"
    echo -e "  ${GREEN}位置:${RESET} ${KEY_PATH}.pub"
    echo -e "  ${GREEN}权限:${RESET} 644 (所有者读写，其他只读)"
    
    if [ -f "$KEY_DIR/$PUTTY_KEY" ]; then
        echo -e "\n${BOLD}${WHITE}PuTTY 格式密钥:${RESET}"
        echo -e "  ${YELLOW}⚡ 用于Windows PuTTY客户端${RESET}"
        echo -e "  ${GREEN}位置:${RESET} $KEY_DIR/$PUTTY_KEY"
    fi
    
    if [ -f "$KEY_DIR/$PEM_KEY" ]; then
        echo -e "\n${BOLD}${WHITE}PEM 格式密钥:${RESET}"
        echo -e "  ${MAGENTA}🔄 兼容OpenSSH格式${RESET}"
        echo -e "  ${GREEN}位置:${RESET} $KEY_DIR/$PEM_KEY"
    fi
    
    echo -e "\n${CYAN}────────────────────────────────────────${RESET}"
    
    # 公钥信息
    echo -e "\n${BOLD}${GREEN}🔐 公钥信息:${RESET}"
    echo -e "${CYAN}────────────────────────────────────────${RESET}"
    
    echo -e "${BOLD}${WHITE}公钥内容:${RESET}"
    echo -e "${YELLOW}$(cat "$KEY_PATH.pub")${RESET}"
    
    echo -e "\n${BOLD}${WHITE}密钥指纹:${RESET}"
    FINGERPRINT=$(ssh-keygen -lf "$KEY_PATH.pub" 2>/dev/null | head -1)
    if [ -n "$FINGERPRINT" ]; then
        echo -e "  ${GREEN}${FINGERPRINT}${RESET}"
    else
        echo -e "  ${YELLOW}无法获取密钥指纹${RESET}"
    fi
    
    echo -e "\n${BOLD}${WHITE}公钥已导入:${RESET}"
    echo -e "  ${GREEN}${AUTH_KEYS}${RESET}"
    echo -e "  ${YELLOW}（已启用此密钥的SSH免密登录）${RESET}"
    
    # 使用示例
    echo -e "\n${CYAN}────────────────────────────────────────${RESET}"
    echo -e "\n${BOLD}${GREEN}🚀 使用示例:${RESET}"
    echo -e "${CYAN}────────────────────────────────────────${RESET}"
    
    echo -e "${BOLD}${WHITE}1. 通过SSH连接服务器:${RESET}"
    echo -e "  ${YELLOW}ssh -i ${KEY_PATH} 用户名@服务器IP${RESET}"
    
    echo -e "\n${BOLD}${WHITE}2. 复制公钥到其他服务器:${RESET}"
    echo -e "  ${YELLOW}ssh-copy-id -i ${KEY_PATH} 用户名@服务器IP${RESET}"
    echo -e "  ${YELLOW}或手动添加公钥到远程服务器的 ~/.ssh/authorized_keys${RESET}"
    
    echo -e "\n${BOLD}${WHITE}3. 在config文件中使用:${RESET}"
    echo -e "  ${YELLOW}# 编辑 ~/.ssh/config${RESET}"
    echo -e "  ${YELLOW}Host myserver${RESET}"
    echo -e "  ${YELLOW}  HostName 服务器IP${RESET}"
    echo -e "  ${YELLOW}  User 用户名${RESET}"
    echo -e "  ${YELLOW}  IdentityFile ${KEY_PATH}${RESET}"
    
    if [ -f "$KEY_DIR/$PUTTY_KEY" ]; then
        echo -e "\n${BOLD}${WHITE}4. PuTTY使用:${RESET}"
        echo -e "  ${YELLOW}a) 打开PuTTY${RESET}"
        echo -e "  ${YELLOW}b) 连接 → SSH → 认证${RESET}"
        echo -e "  ${YELLOW}c) 点击"浏览"导入: $PUTTY_KEY${RESET}"
    fi
    
    # 安全提醒
    echo -e "\n${CYAN}────────────────────────────────────────${RESET}"
    echo -e "\n${BOLD}${RED}⚠ 重要安全提醒:${RESET}"
    echo -e "${RED}────────────────────────────────────────${RESET}"
    echo -e "${RED}1. ${BOLD}私钥保密${RESET}: 切勿将私钥文件分享给他人${RESET}"
    echo -e "${RED}2. ${BOLD}安全备份${RESET}: 备份私钥到加密的USB或密码管理器${RESET}"
    echo -e "${RED}3. ${BOLD}权限检查${RESET}: 确保私钥权限为600，目录权限为700${RESET}"
    echo -e "${RED}4. ${BOLD}密钥轮换${RESET}: 建议每6-12个月更换一次密钥${RESET}"
    echo -e "${RED}5. ${BOLD}测试连接${RESET}: 立即测试密钥连接，确认正常后再关闭当前会话${RESET}"
    
    # 验证密钥有效性
    echo -e "\n${CYAN}────────────────────────────────────────${RESET}"
    echo -e "\n${BOLD}${GREEN}✅ 密钥验证:${RESET}"
    echo -e "${CYAN}────────────────────────────────────────${RESET}"
    
    if [ -f "$KEY_PATH" ] && [ -f "$KEY_PATH.pub" ]; then
        echo -e "  ${ICON_OK} ${GREEN}私钥和公钥文件存在且完整${RESET}"
        
        # 验证密钥格式
        if ssh-keygen -l -f "$KEY_PATH" >/dev/null 2>&1; then
            echo -e "  ${ICON_OK} ${GREEN}私钥格式有效${RESET}"
        else
            echo -e "  ${ICON_ERROR} ${YELLOW}私钥格式可能损坏${RESET}"
        fi
        
        # 验证公钥格式
        if ssh-keygen -l -f "$KEY_PATH.pub" >/dev/null 2>&1; then
            echo -e "  ${ICON_OK} ${GREEN}公钥格式有效${RESET}"
        else
            echo -e "  ${ICON_ERROR} ${YELLOW}公钥格式可能损坏${RESET}"
        fi
        
        # 检查authorized_keys
        if grep -q "$(cat "$KEY_PATH.pub" | cut -d' ' -f2)" "$AUTH_KEYS" 2>/dev/null; then
            echo -e "  ${ICON_OK} ${GREEN}公钥已正确导入authorized_keys${RESET}"
        else
            echo -e "  ${ICON_WARN} ${YELLOW}公钥可能未导入authorized_keys${RESET}"
        fi
        
    else
        echo -e "  ${ICON_ERROR} ${RED}密钥文件不完整，请重新生成${RESET}"
    fi
    
    echo -e "\n${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${WHITE}           密钥创建流程完成！           ${RESET}"
    echo -e "${BOLD}${YELLOW}      请妥善保管您的私钥文件！         ${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    
    read -n 1 -s -r -p "按任意键继续..."
}


# 功能2: SSH安全配置
function_ssh_config() {
    # 使用heredoc来避免引号问题
    sudo bash << 'EOF'
# 颜色定义
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
MAGENTA="\033[35m"
CYAN="\033[36m"
WHITE="\033[37m"
BOLD="\033[1m"
UNDERLINE="\033[4m"
RESET="\033[0m"

# 图标定义
ICON_OK="${GREEN}✓${RESET}"
ICON_WARN="${YELLOW}⚠${RESET}"
ICON_ERROR="${RED}✗${RESET}"
ICON_INFO="${BLUE}ℹ${RESET}"
ICON_CONFIG="${CYAN}⚙${RESET}"
ICON_FOLDER="${MAGENTA}📁${RESET}"

config_file="/etc/ssh/sshd_config"
backup_file="$config_file.$(date +%Y%m%d%H%M%S).bak"

# 安全配置参数
declare -a kv_pairs=(
  "PubkeyAuthentication yes"
  "PasswordAuthentication no" 
  "PermitRootLogin prohibit-password"
  "PermitEmptyPasswords no"
)

echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}${WHITE}             SSH安全配置              ${RESET}"
echo -e "${BOLD}${YELLOW}目的: 关闭密码认证,允许密钥登陆,禁用空密码${RESET}"
echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n"

# 创建修改标记数组
declare -A modified

# 备份原配置文件
if cp "$config_file" "$backup_file" 2>/dev/null; then
    echo -e "${ICON_INFO} 配置文件已备份至: ${WHITE}$backup_file${RESET}\n"
else
    echo -e "${ICON_WARN} 注意：无法创建备份，继续执行...\n"
fi

# 检查是否需要修改
has_changes=false
for kv in "${kv_pairs[@]}"; do
  key="${kv%% *}"
  val="${kv#* }"
  current_line=$(grep -E "^[#[:space:]]*$key" "$config_file" 2>/dev/null | head -1)
  if [ -n "$current_line" ] && [ "$(echo "$current_line" | tr -d '[:space:]')" = "$(echo "$key $val" | tr -d '[:space:]')" ]; then
    # 配置已正确设置，无需修改
    modified[$key]=0
  else
    has_changes=true
  fi
done

if [ "$has_changes" = true ]; then
  echo -e "${ICON_CONFIG} ${BOLD}更新SSH配置:${RESET}"
  echo -e "${BLUE}────────────────────────────────────────${RESET}"
  for kv in "${kv_pairs[@]}"; do
    key="${kv%% *}"
    val="${kv#* }"
    before=$(grep -E "^[#[:space:]]*$key" "$config_file" 2>/dev/null | head -1 | sed "s/^[[:space:]]*//")
    [ -z "$before" ] && before="${YELLOW}(未设置)${RESET}"
    
    # 检查当前配置是否与目标相同
    current_clean=$(echo "$before" | tr -d '[:space:]' | grep -o "^[^#]*" | sed "s/^[[:space:]]*//;s/[[:space:]]*$//")
    target_clean=$(echo "$key $val" | tr -d '[:space:]')  # 修复了这里的引号错误！
    
    if [ "$current_clean" = "$target_clean" ] || ([ -n "$current_clean" ] && [ "$current_clean" = "#$target_clean" ]); then
      # 配置已正确设置，无需修改
      modified[$key]=0
    else
      # 需要修改
      modified[$key]=1
      if grep -q "^[#[:space:]]*$key" "$config_file"; then
        sed -i "s|^[#[:space:]]*$key.*|$key $val|" "$config_file"
      else
        echo "$key $val" >> "$config_file"
      fi
    fi
    
    after=$(grep -E "^[#[:space:]]*$key" "$config_file" 2>/dev/null | head -1 | sed "s/^[[:space:]]*//")
    
    # 为每个参数添加中文说明
    case $key in
      "PubkeyAuthentication")
        cn_name="密钥认证"
        color="${GREEN}"
        ;;
      "PasswordAuthentication")
        cn_name="密码认证"
        color="${RED}"
        ;;
      "PermitRootLogin")
        cn_name="root登录"
        color="${YELLOW}"
        ;;
      "PermitEmptyPasswords")
        cn_name="空密码"
        color="${RED}"
        ;;
      *)
        cn_name="$key"
        color="${WHITE}"
        ;;
    esac
    
    # 美化前后值显示
    before_display="$before"
    if [[ "$before" =~ ^# ]] && [[ "$after" =~ ^[^#] ]]; then
      # 从注释变为非注释
      after_display="${GREEN}${after}${RESET}"
    elif [[ "$before" =~ ^[[:space:]]*$ ]] && [[ -n "$after" ]]; then
      # 从未设置到设置
      after_display="${GREEN}${after}${RESET}"
    elif [[ "$before" != "$after" ]]; then
      # 值改变
      after_display="${GREEN}${after}${RESET}"
    else
      # 无变化
      after_display="${WHITE}${after}${RESET}"
    fi
    
    # 添加修改标记
    if [ "${modified[$key]}" = "1" ]; then
      echo -e "  ${BOLD}${color}${cn_name}${RESET}: ${before_display} ${BOLD}→${RESET} ${after_display} ${ICON_OK}"
    else
      echo -e "  ${BOLD}${color}${cn_name}${RESET}: ${before_display} ${BOLD}→${RESET} ${after_display}"
    fi
  done
  echo -e "${BLUE}────────────────────────────────────────${RESET}"
else
  echo -e "${ICON_OK} ${BOLD}${GREEN}SSH配置已是最新状态，无需修改${RESET}"
  echo -e "${BLUE}────────────────────────────────────────${RESET}"
  echo -e "${BOLD}当前配置:${RESET}"
  for kv in "${kv_pairs[@]}"; do
    key="${kv%% *}"
    val="${kv#* }"
    current_line=$(grep -E "^[#[:space:]]*$key" "$config_file" 2>/dev/null | head -1 | sed "s/^[[:space:]]*//")
    [ -z "$current_line" ] && current_line="${YELLOW}(未设置)${RESET}"
    
    case $key in
      "PubkeyAuthentication")
        cn_name="密钥认证"
        color="${GREEN}"
        ;;
      "PasswordAuthentication")
        cn_name="密码认证"
        color="${RED}"
        ;;
      "PermitRootLogin")
        cn_name="root登录"
        color="${YELLOW}"
        ;;
      "PermitEmptyPasswords")
        cn_name="空密码"
        color="${RED}"
        ;;
      *)
        cn_name="$key"
        color="${WHITE}"
        ;;
    esac
    
    # 检查配置是否正确
    if [[ "$current_line" =~ ^# ]]; then
      # 注释状态
      line_color="${YELLOW}"
    elif [[ "$current_line" =~ $key[[:space:]]+$val ]]; then
      # 配置正确
      line_color="${GREEN}"
    else
      # 配置错误
      line_color="${RED}"
    fi
    
    echo -e "  ${BOLD}${color}${cn_name}${RESET}: ${line_color}${current_line}${RESET}"
  done
  echo -e "${BLUE}────────────────────────────────────────${RESET}"
fi

# 统计修改数量
modified_count=0
for key in "${!modified[@]}"; do
  if [ "${modified[$key]}" = "1" ]; then
    modified_count=$((modified_count + 1))
  fi
done

# 检查配置目录中的潜在冲突
has_conflicts=false
for conf_dir in /etc/ssh/ssh_config.d /etc/ssh/sshd_config.d; do
  if [ -d "$conf_dir" ]; then
    find "$conf_dir" -name "*.conf" -type f 2>/dev/null | while read -r conf; do
      for kv in "${kv_pairs[@]}"; do
        key="${kv%% *}"
        if grep -q "^[#[:space:]]*$key" "$conf" 2>/dev/null; then
          has_conflicts=true
          echo -e "${ICON_WARN} ${YELLOW}警告:${RESET} ${WHITE}$conf${RESET} 中包含 ${RED}${key}${RESET} 设置，可能与主配置冲突"
        fi
      done
    done
  fi
done

# 验证并应用配置
echo -e "\n${ICON_INFO} ${BOLD}验证配置...${RESET}"
if sshd -t 2>/dev/null; then
    echo -e "  ${ICON_OK} ${GREEN}配置语法验证通过${RESET}"
  if [ "$has_changes" = true ] && [ $modified_count -gt 0 ]; then
    if systemctl reload sshd 2>/dev/null || systemctl restart sshd 2>/dev/null; then
        echo -e "\n${ICON_OK} ${BOLD}${GREEN}SSH配置已更新并重新加载${RESET}"
        echo -e "  ${GREEN}修改了 ${BOLD}${modified_count}${RESET}${GREEN} 个配置项${RESET}"
    else
        echo -e "\n${ICON_ERROR} ${BOLD}${RED}SSH服务重载失败，请手动检查！${RESET}"
    fi
  elif [ "$has_changes" = true ]; then
    echo -e "\n${ICON_INFO} ${BOLD}配置无变化，无需重新加载${RESET}"
  fi
  
  # 列出配置目录文件内容
  echo -e "\n${ICON_INFO} ${BOLD}${MAGENTA}检查配置目录:${RESET}"
  for conf_dir in /etc/ssh/ssh_config.d /etc/ssh/sshd_config.d; do
    if [ -d "$conf_dir" ]; then
      echo -e "\n${BOLD}${WHITE}目录:${RESET} ${CYAN}$conf_dir${RESET}"
      if [ "$(find "$conf_dir" -name "*.conf" 2>/dev/null | wc -l)" -gt 0 ]; then
        for conf_file in "$conf_dir"/*.conf; do
          if [ -f "$conf_file" ]; then
            echo -e "\n${BOLD}文件:${RESET} ${WHITE}$conf_file${RESET}"
            echo -e "${BLUE}────────────────────────────────────────${RESET}"
            cat "$conf_file" 2>/dev/null | head -10 || echo -e "${YELLOW}无法读取文件或文件为空${RESET}"
          fi
        done
      else
        echo -e "  ${WHITE}(无配置文件)${RESET}"
      fi
    fi
  done
  
  # 最终提示
  echo -e "\n${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  if [ "$has_conflicts" = true ]; then
    echo -e "${ICON_WARN} ${YELLOW}注意:${RESET} 检测到配置目录中有冲突设置，请检查！"
  fi
  if [ $modified_count -gt 0 ]; then
    echo -e "${ICON_OK} ${GREEN}配置修改摘要:${RESET}"
    for kv in "${kv_pairs[@]}"; do
      key="${kv%% *}"
      if [ "${modified[$key]}" = "1" ]; then
        case $key in
          "PubkeyAuthentication")
            cn_name="密钥认证"
            echo -e "  ${GREEN}✓${RESET} ${cn_name} 已启用"
            ;;
          "PasswordAuthentication")
            cn_name="密码认证"
            echo -e "  ${RED}✓${RESET} ${cn_name} 已禁用"
            ;;
          "PermitRootLogin")
            cn_name="root登录"
            echo -e "  ${YELLOW}✓${RESET} ${cn_name} 已限制为密钥认证"
            ;;
          "PermitEmptyPasswords")
            cn_name="空密码"
            echo -e "  ${RED}✓${RESET} ${cn_name} 已禁止"
            ;;
        esac
      fi
    done
  fi
  echo -e "${ICON_INFO} ${BOLD}重要提醒:${RESET}"
  echo -e "  ${BOLD}•${RESET} 请确保已添加SSH公钥到 ${UNDERLINE}~/.ssh/authorized_keys${RESET}"
  echo -e "  ${BOLD}•${RESET} 建议在断开当前连接前，新开终端测试SSH连接"
  echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
else
  echo -e "\n${ICON_ERROR} ${BOLD}${RED}SSH配置测试失败，已恢复备份！${RESET}"
  cp "$backup_file" "$config_file" 2>/dev/null
  echo -e "${ICON_INFO} ${BOLD}请手动检查:${RESET} ${UNDERLINE}sudo sshd -t${RESET}"
  exit 1
fi
EOF
    
    read -n 1 -s -r -p "按任意键继续..."
}


# 功能3: 查看SSH配置详情 (已按您的要求优化)
function_show_config() {
    echo -e "\n${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${WHITE}           SSH配置详情与状态           ${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n"

    # 检查配置文件是否存在
    if [ ! -f "/etc/ssh/sshd_config" ]; then
        echo -e "${ICON_ERROR} ${RED}SSH配置文件不存在: /etc/ssh/sshd_config${RESET}"
        read -n 1 -s -r -p "按任意键继续..."
        return
    fi

    echo -e "${ICON_INFO} ${BOLD}${WHITE}重要配置项概览:${RESET}"
    echo -e "${BLUE}════════════════════════════════════════${RESET}"

    # 定义要检查的关键配置项及其说明
    declare -A config_items=(
        ["Port"]="SSH服务端口; 默认22，建议修改为高端口(>1024)以提高安全性。"
        ["Protocol"]="SSH协议版本; 应设置为 '2' 以禁用不安全的SSH1。"
        ["PermitRootLogin"]="Root用户登录; 建议为 'prohibit-password' 或 'no'，禁止密码登录。"
        ["PubkeyAuthentication"]="公钥认证; 必须为 'yes' 以启用密钥登录。"
        ["PasswordAuthentication"]="密码认证; 强烈建议设为 'no' 以禁用密码登录，防暴力破解。"
        ["PermitEmptyPasswords"]="空密码登录; 必须为 'no'，禁止无密码登录。"
        ["X11Forwarding"]="X11图形转发; 若无图形需求，建议设为 'no' 以减少攻击面。"
        ["ClientAliveInterval"]="客户端活动检测间隔(秒); 设置如 '300' 可断开无响应连接。"
        ["ClientAliveCountMax"]="活动检测次数; 与上项配合，决定断开连接前的总时长。"
        ["MaxAuthTries"]="最大认证尝试次数; 建议设为 '3' 或更低，防暴力破解。"
        ["AllowUsers"]="允许登录的用户; 明确指定用户(如 'AllowUsers admin')可增强安全性。"
        ["DenyUsers"]="拒绝登录的用户; 用于封禁特定用户。"
    )

    # 读取主配置文件
    for key in "${!config_items[@]}"; do
        # 从主配置中查找
        main_value=$(grep -E "^[[:space:]]*$key[[:space:]]+" /etc/ssh/sshd_config 2>/dev/null | head -1 | awk '{for(i=2;i<=NF;i++) printf $i" "; print ""}' | sed 's/[[:space:]]*$//')
        desc="${config_items[$key]}"
        cn_name="${desc%%;*}"
        explanation="${desc#*; }"

        # 如果主配置没有，检查配置文件目录
        if [ -z "$main_value" ]; then
            for conf_dir in /etc/ssh/sshd_config.d /etc/ssh/ssh_config.d; do
                if [ -d "$conf_dir" ]; then
                    for conf_file in "$conf_dir"/*.conf; do
                        [ -f "$conf_file" ] || continue
                        dir_value=$(grep -E "^[[:space:]]*$key[[:space:]]+" "$conf_file" 2>/dev/null | head -1 | awk '{for(i=2;i<=NF;i++) printf $i" "; print ""}' | sed 's/[[:space:]]*$//')
                        [ -n "$dir_value" ] && main_value="[来自 $conf_file] $dir_value" && break 2
                    done
                fi
            done
        fi

        # 如果仍未找到，检查是否被注释
        if [ -z "$main_value" ]; then
            commented_value=$(grep -E "^[[:space:]]*#.*$key[[:space:]]+" /etc/ssh/sshd_config 2>/dev/null | head -1 | sed 's/^[[:space:]]*#//' | awk '{for(i=2;i<=NF;i++) printf $i" "; print ""}' | sed 's/[[:space:]]*$//')
            if [ -n "$commented_value" ]; then
                main_value="${YELLOW}# $commented_value (被注释)${RESET}"
            else
                main_value="${YELLOW}(使用默认值)${RESET}"
            fi
        fi

        # 安全评估与颜色
        case $key in
            "PasswordAuthentication"|"PermitEmptyPasswords")
                if [[ "$main_value" =~ ^(no|NO|No)$ ]]; then
                    status_color="${GREEN}"
                    status="[安全]"
                else
                    status_color="${RED}"
                    status="[风险]"
                fi
                ;;
            "PubkeyAuthentication"|"Protocol")
                if [[ "$main_value" =~ ^(yes|YES|Yes|2)$ ]]; then
                    status_color="${GREEN}"
                    status="[安全]"
                else
                    status_color="${RED}"
                    status="[风险]"
                fi
                ;;
            "PermitRootLogin")
                if [[ "$main_value" =~ ^(no|prohibit-password|without-password)$ ]]; then
                    status_color="${GREEN}"
                    status="[安全]"
                elif [[ "$main_value" =~ ^(yes|YES|Yes)$ ]]; then
                    status_color="${RED}"
                    status="[高危]"
                else
                    status_color="${YELLOW}"
                    status="[注意]"
                fi
                ;;
            *)
                status_color="${CYAN}"
                status=""
                ;;
        esac

        echo -e "  ${BOLD}${WHITE}${key}${RESET}"
        echo -e "      ${CYAN}说明:${RESET} $cn_name"
        echo -e "      ${MAGENTA}作用:${RESET} $explanation"
        echo -e "      ${GREEN}当前值:${RESET} $status_color$main_value${RESET} ${status_color}$status${RESET}\n"
    done

    echo -e "${BLUE}════════════════════════════════════════${RESET}"

    # 服务状态检查
    echo -e "\n${ICON_INFO} ${BOLD}${WHITE}SSH服务状态:${RESET}"
    echo -e "${CYAN}────────────────────────────────────────${RESET}"
    
    SSH_SERVICE=""
    if systemctl list-unit-files | grep -q "sshd.service"; then
        SSH_SERVICE="sshd"
    elif systemctl list-unit-files | grep -q "ssh.service"; then
        SSH_SERVICE="ssh"
    fi
    
    if [ -n "$SSH_SERVICE" ]; then
        if systemctl is-active --quiet $SSH_SERVICE; then
            echo -e "  ${GREEN}● 服务运行中 ($SSH_SERVICE)${RESET}"
        else
            echo -e "  ${RED}● 服务未运行 ($SSH_SERVICE)${RESET}"
        fi
        
        if systemctl is-enabled --quiet $SSH_SERVICE; then
            echo -e "  ${GREEN}● 已启用开机自启${RESET}"
        else
            echo -e "  ${YELLOW}● 未启用开机自启${RESET}"
        fi
    else
        echo -e "  ${RED}● 未找到systemd服务${RESET}"
    fi

    # 监听端口
    SSH_PORT=$(grep -E "^[[:space:]]*Port[[:space:]]+" /etc/ssh/sshd_config 2>/dev/null | head -1 | awk '{print $2}')
    SSH_PORT=${SSH_PORT:-22}
    echo -e "  ${CYAN}● 监听端口:${RESET} $SSH_PORT"
    
    echo -e "\n${YELLOW}提示:${RESET} 查看完整配置: ${UNDERLINE}cat /etc/ssh/sshd_config${RESET}"
    echo -e "      包含目录配置: ${UNDERLINE}ls -la /etc/ssh/sshd_config.d/${RESET} (如果存在)"
    echo -e "${BLUE}────────────────────────────────────────${RESET}"
    read -n 1 -s -r -p "按任意键继续..."
}

# 新功能: 修改SSH端口 (按您的要求新增)
function_change_port() {
    echo -e "\n${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${WHITE}            修改SSH端口             ${RESET}"
    echo -e "${BOLD}${YELLOW}  更改默认SSH端口以增强安全性      ${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n"

    # 获取当前端口
    CURRENT_PORT=$(grep -E "^[[:space:]]*Port[[:space:]]+" /etc/ssh/sshd_config 2>/dev/null | head -1 | awk '{print $2}')
    CURRENT_PORT=${CURRENT_PORT:-22}
    echo -e "${ICON_INFO} ${BOLD}当前SSH端口:${RESET} ${GREEN}${CURRENT_PORT}${RESET}"

    # 获取新端口
    while true; do
        echo -e "\n${ICON_INFO} ${BOLD}请输入新的SSH端口 (1-65535)${RESET}"
        echo -e "  ${YELLOW}提示: 建议使用 1024-65535 之间的端口${RESET}"
        echo -n "  新端口: "
        read -r NEW_PORT

        # 验证端口号
        if [[ ! "$NEW_PORT" =~ ^[0-9]+$ ]] || [ "$NEW_PORT" -lt 1 ] || [ "$NEW_PORT" -gt 65535 ]; then
            echo -e "  ${ICON_ERROR} ${RED}端口号必须在 1-65535 之间${RESET}"
            continue
        fi

        if [ "$NEW_PORT" -eq "$CURRENT_PORT" ]; then
            echo -e "  ${ICON_WARN} ${YELLOW}新端口与当前端口相同，无需修改${RESET}"
            read -n 1 -s -r -p "按任意键继续..."
            return
        fi

        # 检查端口是否已被占用
        if ss -tulpn 2>/dev/null | grep -q ":${NEW_PORT} "; then
            SERVICE=$(ss -tulpn 2>/dev/null | grep ":${NEW_PORT} " | awk '{print $6}')
            echo -e "  ${ICON_ERROR} ${RED}端口 ${NEW_PORT} 已被占用: ${SERVICE}${RESET}"
            echo -e "  ${YELLOW}请选择其他端口${RESET}"
            continue
        fi

        break
    done

    echo -e "\n${ICON_WARN} ${YELLOW}警告: 修改端口后，必须使用新端口进行SSH连接！${RESET}"
    echo -e "  ${YELLOW}例如: ssh -p ${NEW_PORT} username@server_ip${RESET}"
    echo -n -e "\n${BOLD}是否继续? (y/N): ${RESET}"
    read -r CONFIRM
    if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
        echo -e "${ICON_INFO} 操作已取消"
        read -n 1 -s -r -p "按任意键继续..."
        return
    fi

    # 备份并修改配置
    CONFIG_FILE="/etc/ssh/sshd_config"
    BACKUP_FILE="${CONFIG_FILE}.backup.$(date +%Y%m%d%H%M%S)"
    
    echo -e "\n${ICON_INFO} ${BOLD}备份配置文件...${RESET}"
    if sudo cp "$CONFIG_FILE" "$BACKUP_FILE"; then
        echo -e "  ${ICON_OK} 备份成功: ${BACKUP_FILE}"
    else
        echo -e "  ${ICON_ERROR} ${RED}备份失败，操作中止${RESET}"
        read -n 1 -s -r -p "按任意键继续..."
        return
    fi

    echo -e "\n${ICON_INFO} ${BOLD}修改端口配置...${RESET}"
    # 如果已有Port行，则替换；否则添加
    if grep -q "^[[:space:]]*Port[[:space:]]" "$CONFIG_FILE"; then
        sudo sed -i "s/^[[:space:]]*Port[[:space:]].*/Port ${NEW_PORT}/" "$CONFIG_FILE"
        echo -e "  ${ICON_OK} 更新现有端口配置"
    else
        echo -e "\n# 修改SSH端口" | sudo tee -a "$CONFIG_FILE" > /dev/null
        echo "Port ${NEW_PORT}" | sudo tee -a "$CONFIG_FILE" > /dev/null
        echo -e "  ${ICON_OK} 添加新端口配置"
    fi

    # 验证配置
    echo -e "\n${ICON_INFO} ${BOLD}验证配置...${RESET}"
    if sudo sshd -t 2>/dev/null; then
        echo -e "  ${ICON_OK} 配置语法正确"
    else
        echo -e "  ${ICON_ERROR} ${RED}配置语法错误，已恢复备份${RESET}"
        sudo mv "$BACKUP_FILE" "$CONFIG_FILE"
        read -n 1 -s -r -p "按任意键继续..."
        return
    fi

    # 询问是否更新防火墙
    echo -n -e "\n${BOLD}是否更新防火墙规则以允许新端口 ${NEW_PORT}? (y/N): ${RESET}"
    read -r UPDATE_FW
    
    if [[ "$UPDATE_FW" =~ ^[Yy]$ ]]; then
        echo -e "\n${ICON_INFO} ${BOLD}更新防火墙规则...${RESET}"
        
        # 检测并更新UFW
        if command -v ufw >/dev/null 2>&1; then
            echo -e "  ${ICON_INFO} 检测到UFW防火墙"
            if sudo ufw allow "${NEW_PORT}/tcp"; then
                echo -e "  ${ICON_OK} UFW: 已允许端口 ${NEW_PORT}/tcp"
            else
                echo -e "  ${ICON_ERROR} ${YELLOW}UFW: 规则更新失败${RESET}"
            fi
        fi
        
        # 检测并更新firewalld
        if command -v firewall-cmd >/dev/null 2>&1; then
            echo -e "  ${ICON_INFO} 检测到firewalld"
            if sudo firewall-cmd --permanent --add-port="${NEW_PORT}/tcp" 2>/dev/null; then
                sudo firewall-cmd --reload 2>/dev/null
                echo -e "  ${ICON_OK} firewalld: 已永久开放端口 ${NEW_PORT}/tcp"
            else
                echo -e "  ${ICON_ERROR} ${YELLOW}firewalld: 规则更新失败${RESET}"
            fi
        fi
        
        # 检测iptables
        if command -v iptables >/dev/null 2>&1 && ! command -v ufw >/dev/null 2>&1 && ! command -v firewall-cmd >/dev/null 2>&1; then
            echo -e "  ${ICON_INFO} 检测到iptables"
            echo -e "  ${YELLOW}请手动执行以下命令:${RESET}"
            echo -e "  ${CYAN}  sudo iptables -A INPUT -p tcp --dport ${NEW_PORT} -j ACCEPT${RESET}"
            echo -e "  ${YELLOW}并保存规则以便永久生效${RESET}"
        fi
    else
        echo -e "  ${ICON_WARN} ${YELLOW}跳过防火墙更新，请确保新端口 ${NEW_PORT} 在防火墙中已开放${RESET}"
    fi

    # 重启SSH服务
    echo -e "\n${ICON_INFO} ${BOLD}重新加载SSH服务...${RESET}"
    if sudo systemctl reload sshd 2>/dev/null || sudo systemctl restart sshd 2>/dev/null || sudo systemctl restart ssh 2>/dev/null; then
        echo -e "  ${ICON_OK} ${GREEN}SSH服务已重启${RESET}"
    else
        echo -e "  ${ICON_ERROR} ${RED}SSH服务重启失败，请手动检查${RESET}"
    fi

    # 显示结果
    echo -e "\n${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${WHITE}             端口修改完成！              ${RESET}"
    echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${ICON_INFO} ${BOLD}变更摘要:${RESET}"
    echo -e "  ${GREEN}旧端口:${RESET} ${CURRENT_PORT}"
    echo -e "  ${GREEN}新端口:${RESET} ${NEW_PORT}"
    echo -e "  ${GREEN}配置文件备份:${RESET} ${BACKUP_FILE}"
    echo -e "\n${ICON_WARN} ${YELLOW}重要提醒:${RESET}"
    echo -e "  ${RED}1.${RESET} 从现在起，必须使用新端口连接: ${UNDERLINE}ssh -p ${NEW_PORT} 用户名@服务器IP${RESET}"
    echo -e "  ${RED}2.${RESET} 请确保防火墙已开放端口: ${UNDERLINE}${NEW_PORT}/tcp${RESET}"
    echo -e "  ${RED}3.${RESET} 建议在断开当前连接前，用新开终端测试连接"
    echo -e "\n${BOLD}${RED}⚠ 警告: 修改端口后，请立即用新端口测试连接，确认无误后再关闭当前会话！${RESET}"
    
    read -n 1 -s -r -p "按任意键继续..."
}

# 主菜单 (已按您的要求优化布局)
main_menu() {
    while true; do
        show_banner
        
        echo -e "${BOLD}${WHITE}请选择要执行的功能:${RESET}\n"
        echo -e "  ${GREEN}1)${RESET} 创建SSH密钥对"
        echo -e "  ${GREEN}2)${RESET} 配置SSH安全设置"
        echo -e "  ${GREEN}3)${RESET} 查看SSH配置详情"
        echo -e "  ${GREEN}4)${RESET} 修改SSH端口\n"  # 新增功能
        
        # 按照您的要求设置退出选项的样式
        echo -e "\n  ${BOLD}${RED}0)${RESET} ${YELLOW}退出脚本${RESET}\n"
        
        echo -n "请输入选项 (0-4): "
        read -r MENU_CHOICE
        
        case $MENU_CHOICE in
            1)
                function_create_keys
                ;;
            2)
                function_ssh_config
                ;;
            3)
                function_show_config
                ;;
            4)
                function_change_port
                ;;
            0)
                echo -e "\n${ICON_OK} ${GREEN}感谢使用，再见！${RESET}\n"
                exit 0
                ;;
            *)
                echo -e "\n${ICON_ERROR} ${RED}无效选项，请重新选择${RESET}"
                sleep 2
                ;;
        esac
    done
}

# 检查是否以root运行
if [ "$EUID" -ne 0 ]; then
    echo -e "${ICON_WARN} ${YELLOW}建议使用root权限运行此脚本${RESET}"
    echo -e "  某些功能可能需要sudo权限"
    echo -e "  按Ctrl+C取消，或按任意键继续..."
    read -n 1 -s
fi

# 启动主菜单
main_menu
